-- MySQL Script generated by MySQL Workbench
-- Fri Jun 15 14:59:46 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema player-league
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema player-league
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `player-league` DEFAULT CHARACTER SET utf8 ;
USE `player-league` ;

-- -----------------------------------------------------
-- Table `player-league`.`Joueur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `player-league`.`Joueur` (
  `idJoueur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `pseudo` VARCHAR(45) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `rang` INT NOT NULL,
  PRIMARY KEY (`idJoueur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `player-league`.`Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `player-league`.`Equipe` (
  `idEquipe` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `couleur` VARCHAR(45) NOT NULL,
  `embleme` VARCHAR(45) NOT NULL,
  `admin` INT NOT NULL,
  PRIMARY KEY (`idEquipe`),
  INDEX `fk_Equipe_Joueur1_idx` (`admin` ASC),
  CONSTRAINT `fk_Equipe_Joueur1`
    FOREIGN KEY (`admin`)
    REFERENCES `player-league`.`Joueur` (`idJoueur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `player-league`.`Score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `player-league`.`Score` (
  `idScore` INT NOT NULL,
  `Score joueur` INT NOT NULL,
  `Score equipe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idScore`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `player-league`.`Ligue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `player-league`.`Ligue` (
  `idLigue` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLigue`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `player-league`.`Jeu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `player-league`.`Jeu` (
  `idJeu` INT NOT NULL,
  `type de jeu` VARCHAR(45) NOT NULL,
  `Ligue_idLigue` INT NOT NULL,
  PRIMARY KEY (`idJeu`),
  INDEX `fk_Jeu_Ligue1_idx` (`Ligue_idLigue` ASC),
  CONSTRAINT `fk_Jeu_Ligue1`
    FOREIGN KEY (`Ligue_idLigue`)
    REFERENCES `player-league`.`Ligue` (`idLigue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `player-league`.`Match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `player-league`.`Match` (
  `idMatch` INT NOT NULL,
  `map` VARCHAR(45) NOT NULL,
  `temps de jeu` INT NOT NULL,
  `Jeu_idJeu` INT NOT NULL,
  `Joueur_idJoueur1` INT NOT NULL,
  `Joueur_idJoueur2` INT NOT NULL,
  PRIMARY KEY (`idMatch`, `Joueur_idJoueur1`, `Joueur_idJoueur2`),
  INDEX `fk_Match_Jeu1_idx` (`Jeu_idJeu` ASC),
  INDEX `fk_Match_Joueur1_idx` (`Joueur_idJoueur1` ASC),
  INDEX `fk_Match_Joueur2_idx` (`Joueur_idJoueur2` ASC),
  CONSTRAINT `fk_Match_Jeu1`
    FOREIGN KEY (`Jeu_idJeu`)
    REFERENCES `player-league`.`Jeu` (`idJeu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_Joueur1`
    FOREIGN KEY (`Joueur_idJoueur1`)
    REFERENCES `player-league`.`Joueur` (`idJoueur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_Joueur2`
    FOREIGN KEY (`Joueur_idJoueur2`)
    REFERENCES `player-league`.`Joueur` (`idJoueur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `player-league`.`Joueur_has_Score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `player-league`.`Joueur_has_Score` (
  `Joueur_idJoueur` INT NOT NULL,
  `Score_idScore` INT NOT NULL,
  PRIMARY KEY (`Joueur_idJoueur`, `Score_idScore`),
  INDEX `fk_Joueur_has_Score_Score1_idx` (`Score_idScore` ASC),
  INDEX `fk_Joueur_has_Score_Joueur1_idx` (`Joueur_idJoueur` ASC),
  CONSTRAINT `fk_Joueur_has_Score_Joueur1`
    FOREIGN KEY (`Joueur_idJoueur`)
    REFERENCES `player-league`.`Joueur` (`idJoueur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Joueur_has_Score_Score1`
    FOREIGN KEY (`Score_idScore`)
    REFERENCES `player-league`.`Score` (`idScore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `player-league`.`Score_has_Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `player-league`.`Score_has_Equipe` (
  `Score_idScore` INT NOT NULL,
  `Equipe_idEquipe` INT NOT NULL,
  PRIMARY KEY (`Score_idScore`, `Equipe_idEquipe`),
  INDEX `fk_Score_has_Equipe_Equipe1_idx` (`Equipe_idEquipe` ASC),
  INDEX `fk_Score_has_Equipe_Score1_idx` (`Score_idScore` ASC),
  CONSTRAINT `fk_Score_has_Equipe_Score1`
    FOREIGN KEY (`Score_idScore`)
    REFERENCES `player-league`.`Score` (`idScore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Score_has_Equipe_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe`)
    REFERENCES `player-league`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `player-league`.`Joueur_has_Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `player-league`.`Joueur_has_Equipe` (
  `Joueur_idJoueur` INT NOT NULL,
  `Equipe_idEquipe` INT NOT NULL,
  PRIMARY KEY (`Joueur_idJoueur`, `Equipe_idEquipe`),
  INDEX `fk_Joueur_has_Equipe_Equipe1_idx` (`Equipe_idEquipe` ASC),
  INDEX `fk_Joueur_has_Equipe_Joueur1_idx` (`Joueur_idJoueur` ASC),
  CONSTRAINT `fk_Joueur_has_Equipe_Joueur1`
    FOREIGN KEY (`Joueur_idJoueur`)
    REFERENCES `player-league`.`Joueur` (`idJoueur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Joueur_has_Equipe_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe`)
    REFERENCES `player-league`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
